name: frontend
description: A Flutter application for avatar chat using WebRTC

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.46  # Use a stable version
  webrtc_interface: ^1.1.0
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
