#version: '3.8'

services:
  frontend:
    build:
      context: ./flutter_frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge